name: fruitify

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  dots_indicator: ^4.0.1
  smooth_page_indicator: ^2.0.1
  shared_preferences: ^2.5.5
  supabase: ^2.14.0
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  dartz: ^0.10.1
  bloc: ^9.2.1
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  modal_progress_hud_nsn: ^0.5.0
  equatable: ^2.1.0
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^7.2.0
  flutter_screenutil: ^5.9.3
  svg_image_provider: ^0.1.2
  flutter_svg_provider: ^1.0.7
  curved_labeled_navigation_bar: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/vuesax/bold/
    - assets/images/vuesax/outline/



  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
